version: "3.0"
services:
  app:
    restart: always
    build:
      context: app/
    expose:
      - "8000"
    volumes:
      - /usr/src/app
    # env_file:
        # .env
    command: gunicorn example.wsgi:application -w 2 -b :8000 --reload --timeout 300 --workers 3 --pythonpath /example
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    links:
      - app:app
